import type { Metadata } from "next";
import "./globals.css";
import varela_Round from "@/fonts/varela-round";
import { Toaster } from "sonner";
import LayoutWrapper from "./components/layout-wrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${varela_Round.variable}, antialiased`}>
        <LayoutWrapper>{children}</LayoutWrapper>
        <Toaster />
      </body>
    </html>
  );
}
